name: CI-test
on: [push]
jobs:
  run-tests:
    name: run tests
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v3

      - name: install dependencies
        run: python -m pip install pytest gspread python-dotenv pandas==1.2.4

      - name: run tests
        run: pytest
