name: CI-test

# Controls when the action will run.
on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      # setup python with different versions
      - name: setup python version 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"    

      # install poetry
      - name: install poetry
        run: pipx install poetry

      # install dependencies with poetry
      - name: Install dependencies
        run: |
          poetry install

      # run tests with pytest coverage
      - name: run tests with coverage
        run: poetry run pytest --cov
      