name: CI-test

# Controls when the action will run.
on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      # setup python with different versions
      - name: setup python version ${{ matrix.python-version}}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}      

      # install poetry
      - name: install poetry
        run: pipx install poetry

      # install dependencies with poetry
      - name: Install dependencies
        run: |
          poetry install

      # run tests with pytest coverage option
      - name: run tests with coverage
        run: poetry run pytest --cov
      